In [ ]:
import pandas as pd

URL_PREFIX = "https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/"

In [3]:
#graybook = pd.read_html("https://www.trustees.uillinois.edu/trustees/resources/21-22-Graybook/TOC.html")
#graybook = pd.read_html("https://www.trustees.uillinois.edu/trustees/resources/23-24-Graybook/TOC.html")
#graybook = pd.read_html("https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/TOC.html")

f = open("colleges.txt")
colleges = f.readlines()
f.close()
colleges

['KL - Agr, Consumer & Env Sciences\n',
 'KY - Applied Health Sciences\n',
 'LD - Armed Forces\n',
 'NQ - Auxiliary Units\n',
 'LT - Carle Illinois Medicine\n',
 'LN - Center Innov in Teach Learn\n',
 'NA - Chancellor\n',
 'KT - College of Media\n',
 'NU - Div Intercollegiate Athletics\n',
 'KW - Division of Exploratory Studies\n',
 'KN - Education\n',
 'MY - Energy Services\n',
 'NN - Facilities\n',
 'KR - Fine & Applied Arts\n',
 'KM - Gies College of Business\n',
 'KS - Graduate College\n',
 'KP - Grainger Engineering\n',
 'LQ - Illinois International\n',
 'KU - Law\n',
 'KV - Liberal Arts & Sciences\n',
 'NP - OVCRI Institutes\n',
 'NS - Ofc VC Inst Advancement\n',
 'NB - Provost & Executive VC\n',
 'LF - Public Safety\n',
 'LP - School of Information Sciences\n',
 'LG - School of Labor & Empl. Rel.\n',
 'LL - School of Social Work\n',
 'NT - Technology Services\n',
 'LR - University Library\n',
 'NL - VC Admin and Operations\n',
 'NJ - VC Student Affairs\n',
 'NE - VC for Research and Innovation\n',
 'LC - Veterinary Medicine\n',
 'NV - Vice Chancellor for Diversity']

In [ ]:
urlList = []
collegeCodes = []
collegeNames = []
for college in colleges:
  if type(college) == type("string"):
    collegeCode, collegeName = college.strip().split(" - ")
    collegeCodes.append(collegeCode)
    collegeNames.append(collegeName)
    urlList.append(f"{URL_PREFIX}{collegeCode}.html")

In [23]:
# urlList = [ urlList[0] ]
urlList

['https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KL.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KY.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/LD.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NQ.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/LT.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/LN.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NA.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KT.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NU.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KW.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KN.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/MY.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NN.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KR.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KM.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KS.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KP.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/LQ.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KU.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KV.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NP.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NS.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NB.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/LF.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/LP.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/LG.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/LL.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NT.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/LR.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NL.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NJ.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NE.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/LC.html',
 'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/NV.html']

In [24]:
dept_code = None
dept_name = None
def f(row):
  global dept_code
  global dept_name

  if row["Job Title"] == row["Employee Name"]:
    dept_code, dept_name = row["Job Title"].split(" - ")
    row["Department Code"] = None
    row["Department Name"] = None
    return row
  else:
    row["Department Code"] = dept_code
    row["Department Name"] = dept_name
    return row

In [25]:
import requests

In [ ]:
import io

def processPage(rawHTML, collegeCode, collegeName):
  dfs = []
  h3s = rawHTML.split("<h3")
  for index in range(1, len(h3s)):
    h3_split = h3s[index]

    h3_full = "<h3" + h3_split
    h3_split = h3_split[ h3_split.find(">") + 1 : h3_split.find("</h3>") ]
    departmentName = h3_split.split("-")[1].strip()
    print(departmentName)

    buffer = io.StringIO(h3_full)
    df = pd.read_html(buffer)[0]
    df["Department Name"] = departmentName
    df["College Code"] = collegeCode
    df["College Name"] = collegeName
    dfs.append(df)
  return pd.concat(dfs)

In [28]:
urlList[0]

'https://www.trustees.uillinois.edu/trustees/resources/25-26-Graybook/KL.html'

In [29]:
rawHTML = requests.get(urlList[0]).text
rawHTML

'<!DOCTYPE html><html xml:lang="en" lang="en" xmlns="http://www.w3.org/1999/xhtml">\r\n    <head>\r\n        <META http-equiv="Content-Type" content="text/html; charset=utf-8">\r\n        <title>Board of Trustees-University of Illinois: Gray Book</title>\r\n        <link rel="stylesheet" href="graybookfullrpt-styles.css" type="text/css">\r\n        <script>\r\n                function infobox(){\r\n                \talert("To Print this page, use Ctrl+p or the Print menu selection. \\n To find someone on this page, use Ctrl+f or the Find menu selection.");\r\n                }\r\n                </script>\r\n    </head>\r\n    <body>\r\n        <div class="header" xmlns="">\r\n            <span>August 18, 2025</span>\r\n            <h1>Board of Trustees - University of Illinois System: Academic Personnel Supplement 2025-2026</h1>\r\n            <span class="center">(Urbana-Champaign University)</span><span class="right-info-link"><a href="#" onclick="infobox()">Print and Search tips.</a></span>\r\n        </div>\r\n        <div class="back-to-TOC-heading">\r\n            <a href="TOC.html">Back to Table of Contents</a>\r\n        </div>\r\n        <h2 id="c1">KL - Agr, Consumer &amp; Env Sciences</h2>\r\n        <h3 id="c1-d1">348 - ACES Technology Services</h3>\r\n        <table id="c1-d1-salary-table">\r\n            <thead>\r\n                <tr>\r\n                    <th id="c1-d1-empl-header" class="empl-heading">Employee Name</th><th id="c1-d1-job-header" class="job-heading">Job Title</th><th id="c1-d1-tenure-header" class="ten-heading">Tenure</th><th id="c1-d1-empl-class-header" class="empclass-heading">Empl Class</th><th id="c1-d1-presfte-header" class="presfte-heading">Present FTE</th><th id="c1-d1-propfte-header" class="propfte-heading">Proposed FTE</th><th id="c1-d1-pressal-header" class="pressal-heading">Present Salary</th><th id="c1-d1-propsal-header" class="propsal-heading">Proposed Salary</th>\r\n                </tr>\r\n            </thead>\r\n            <tbody>\r\n                <tr id="c1-d1-e1-j1">\r\n                    <td headers="c1-d1-empl-header" class="empl" style="background-color: #ffffff">Kim, James H</td><td headers="c1-d1-job-header" class="job" style="background-color: #ffffff">DIR OF INFO TECHNOL</td><td headers="c1-d1-tenure-header" class="tenure" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d1-empl-class-header" class="empclass" style="background-color: #ffffff">BA</td><td headers="c1-d1-presfte-header" style="background-color: #ffffff">1.00</td><td headers="c1-d1-propfte-header" style="background-color: #ffffff">1.00</td><td headers="c1-d1-pressal-header" class="right" style="background-color: #ffffff">$115,000.00</td><td headers="c1-d1-propsal-header" class="right" style="background-color: #ffffff">$116,150.00</td>\r\n                </tr>\r\n                <tr id="c1-d1-e2-j1">\r\n                    <td headers="c1-d1-empl-header" class="empl" style="background-color: #d3d3d3">Meyer, Donald L</td><td headers="c1-d1-job-header" class="job" style="background-color: #d3d3d3">SR NETWORK ANLYS</td><td headers="c1-d1-tenure-header" class="tenure" style="background-color: #d3d3d3">&nbsp;</td><td headers="c1-d1-empl-class-header" class="empclass" style="background-color: #d3d3d3">BA</td><td headers="c1-d1-presfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d1-propfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d1-pressal-header" class="right" style="background-color: #d3d3d3">$98,328.48</td><td headers="c1-d1-propsal-header" class="right" style="background-color: #d3d3d3">$99,311.76</td>\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n        <h3 id="c1-d2">521 - ADM Institute for PHL</h3>\r\n        <table id="c1-d2-salary-table">\r\n            <thead>\r\n                <tr>\r\n                    <th id="c1-d2-empl-header" class="empl-heading">Employee Name</th><th id="c1-d2-job-header" class="job-heading">Job Title</th><th id="c1-d2-tenure-header" class="ten-heading">Tenure</th><th id="c1-d2-empl-class-header" class="empclass-heading">Empl Class</th><th id="c1-d2-presfte-header" class="presfte-heading">Present FTE</th><th id="c1-d2-propfte-header" class="propfte-heading">Proposed FTE</th><th id="c1-d2-pressal-header" class="pressal-heading">Present Salary</th><th id="c1-d2-propsal-header" class="propsal-heading">Proposed Salary</th>\r\n                </tr>\r\n            </thead>\r\n            <tbody>\r\n                <tr id="c1-d2-e1-j1">\r\n                    <td headers="c1-d2-empl-header" class="empl" style="background-color: #ffffff">McNamara, Paul E</td><td headers="c1-d2-job-header" class="job" style="background-color: #ffffff">DIR, ADMI</td><td headers="c1-d2-tenure-header" class="tenure" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d2-empl-class-header" class="empclass" style="background-color: #ffffff">BA</td><td headers="c1-d2-presfte-header" style="background-color: #ffffff">0.00</td><td headers="c1-d2-propfte-header" style="background-color: #ffffff">0.00</td><td headers="c1-d2-pressal-header" class="right" style="background-color: #ffffff">$15,000.00</td><td headers="c1-d2-propsal-header" class="right" style="background-color: #ffffff">$15,000.00</td>\r\n                </tr>\r\n                <tr id="c1-d2-e1-total">\r\n                    <td headers="c1-d2-empl-header" class="empl" style="background-color: #d3d3d3">McNamara, Paul E</td><td headers="c1-d2-job-header" class="italic-left" style="background-color: #d3d3d3">Employee Total for All Jobs</td><td headers="c1-d2-tenure-header" class="tenure" style="background-color: #d3d3d3">&nbsp;</td><td headers="c1-d2-empl-class-header" class="empclass" style="background-color: #d3d3d3">&nbsp;</td><td headers="c1-d2-presfte-header" class="italic" style="background-color: #d3d3d3">1.00</td><td headers="c1-d2-propfte-header" class="italic" style="background-color: #d3d3d3">1.00</td><td headers="c1-d2-pressal-header" class="italic-right" style="background-color: #d3d3d3">$173,952.40</td><td headers="c1-d2-propsal-header" class="italic-right" style="background-color: #d3d3d3">$175,541.92</td>\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n        <h3 id="c1-d3">342 - Ag Ldrshp Educ Comm Program</h3>\r\n        <table id="c1-d3-salary-table">\r\n            <thead>\r\n                <tr>\r\n                    <th id="c1-d3-empl-header" class="empl-heading">Employee Name</th><th id="c1-d3-job-header" class="job-heading">Job Title</th><th id="c1-d3-tenure-header" class="ten-heading">Tenure</th><th id="c1-d3-empl-class-header" class="empclass-heading">Empl Class</th><th id="c1-d3-presfte-header" class="presfte-heading">Present FTE</th><th id="c1-d3-propfte-header" class="propfte-heading">Proposed FTE</th><th id="c1-d3-pressal-header" class="pressal-heading">Present Salary</th><th id="c1-d3-propsal-header" class="propsal-heading">Proposed Salary</th>\r\n                </tr>\r\n            </thead>\r\n            <tbody>\r\n                <tr id="c1-d3-e1-j1">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #ffffff">Axtman-Barker, Pamela Ann</td><td headers="c1-d3-job-header" class="job" style="background-color: #ffffff">TCH ASST PROF</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #ffffff">AL</td><td headers="c1-d3-presfte-header" style="background-color: #ffffff">1.00</td><td headers="c1-d3-propfte-header" style="background-color: #ffffff">1.00</td><td headers="c1-d3-pressal-header" class="right" style="background-color: #ffffff">$79,950.00</td><td headers="c1-d3-propsal-header" class="right" style="background-color: #ffffff">$83,148.00</td>\r\n                </tr>\r\n                <tr id="c1-d3-e2-j1">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #d3d3d3">Korte, Debra Sue</td><td headers="c1-d3-job-header" class="job" style="background-color: #d3d3d3">TCH ASSOC PROF</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #d3d3d3">M</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #d3d3d3">AA</td><td headers="c1-d3-presfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d3-propfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d3-pressal-header" class="right" style="background-color: #d3d3d3">$102,763.74</td><td headers="c1-d3-propsal-header" class="right" style="background-color: #d3d3d3">$105,332.83</td>\r\n                </tr>\r\n                <tr id="c1-d3-e2-total">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #ffffff">Korte, Debra Sue</td><td headers="c1-d3-job-header" class="italic-left" style="background-color: #ffffff">Employee Total for All Jobs</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d3-presfte-header" class="italic" style="background-color: #ffffff">1.00</td><td headers="c1-d3-propfte-header" class="italic" style="background-color: #ffffff">1.00</td><td headers="c1-d3-pressal-header" class="italic-right" style="background-color: #ffffff">$102,763.74</td><td headers="c1-d3-propsal-header" class="italic-right" style="background-color: #ffffff">$105,332.83</td>\r\n                </tr>\r\n                <tr id="c1-d3-e3-j1">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #d3d3d3">Leman, Amy Marie</td><td headers="c1-d3-job-header" class="job" style="background-color: #d3d3d3">ASST PROF</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #d3d3d3">&nbsp;</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #d3d3d3">AA</td><td headers="c1-d3-presfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d3-propfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d3-pressal-header" class="right" style="background-color: #d3d3d3">$91,829.24</td><td headers="c1-d3-propsal-header" class="right" style="background-color: #d3d3d3">$93,665.82</td>\r\n                </tr>\r\n                <tr id="c1-d3-e3-total">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #ffffff">Leman, Amy Marie</td><td headers="c1-d3-job-header" class="italic-left" style="background-color: #ffffff">Employee Total for All Jobs</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d3-presfte-header" class="italic" style="background-color: #ffffff">1.00</td><td headers="c1-d3-propfte-header" class="italic" style="background-color: #ffffff">1.00</td><td headers="c1-d3-pressal-header" class="italic-right" style="background-color: #ffffff">$91,829.24</td><td headers="c1-d3-propsal-header" class="italic-right" style="background-color: #ffffff">$93,665.82</td>\r\n                </tr>\r\n                <tr id="c1-d3-e4-j1">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #d3d3d3">Morgan, Eric Lee</td><td headers="c1-d3-job-header" class="job" style="background-color: #d3d3d3">ASSOC PROF</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #d3d3d3">&nbsp;</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #d3d3d3">AA</td><td headers="c1-d3-presfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d3-propfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d3-pressal-header" class="right" style="background-color: #d3d3d3">$96,803.17</td><td headers="c1-d3-propsal-header" class="right" style="background-color: #d3d3d3">$97,771.20</td>\r\n                </tr>\r\n                <tr id="c1-d3-e4-total">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #ffffff">Morgan, Eric Lee</td><td headers="c1-d3-job-header" class="italic-left" style="background-color: #ffffff">Employee Total for All Jobs</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d3-presfte-header" class="italic" style="background-color: #ffffff">1.00</td><td headers="c1-d3-propfte-header" class="italic" style="background-color: #ffffff">1.00</td><td headers="c1-d3-pressal-header" class="italic-right" style="background-color: #ffffff">$96,803.17</td><td headers="c1-d3-propsal-header" class="italic-right" style="background-color: #ffffff">$97,771.20</td>\r\n                </tr>\r\n                <tr id="c1-d3-e5-j1">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #d3d3d3">Ochs, Gary Alan</td><td headers="c1-d3-job-header" class="job" style="background-color: #d3d3d3">INSTR</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #d3d3d3">&nbsp;</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #d3d3d3">AL</td><td headers="c1-d3-presfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d3-propfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d3-pressal-header" class="right" style="background-color: #d3d3d3">$85,240.93</td><td headers="c1-d3-propsal-header" class="right" style="background-color: #d3d3d3">$87,371.95</td>\r\n                </tr>\r\n                <tr id="c1-d3-e6-j1">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #ffffff">Rosch, David Michael</td><td headers="c1-d3-job-header" class="job" style="background-color: #ffffff">ASSOC PROF</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #ffffff">AA</td><td headers="c1-d3-presfte-header" style="background-color: #ffffff">1.00</td><td headers="c1-d3-propfte-header" style="background-color: #ffffff">1.00</td><td headers="c1-d3-pressal-header" class="right" style="background-color: #ffffff">$108,226.47</td><td headers="c1-d3-propsal-header" class="right" style="background-color: #ffffff">$109,308.73</td>\r\n                </tr>\r\n                <tr id="c1-d3-e6-total">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #d3d3d3">Rosch, David Michael</td><td headers="c1-d3-job-header" class="italic-left" style="background-color: #d3d3d3">Employee Total for All Jobs</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #d3d3d3">&nbsp;</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #d3d3d3">&nbsp;</td><td headers="c1-d3-presfte-header" class="italic" style="background-color: #d3d3d3">1.00</td><td headers="c1-d3-propfte-header" class="italic" style="background-color: #d3d3d3">1.00</td><td headers="c1-d3-pressal-header" class="italic-right" style="background-color: #d3d3d3">$108,226.47</td><td headers="c1-d3-propsal-header" class="italic-right" style="background-color: #d3d3d3">$109,308.73</td>\r\n                </tr>\r\n                <tr id="c1-d3-e7-j1">\r\n                    <td headers="c1-d3-empl-header" class="empl" style="background-color: #ffffff">Smist, Jennifer Anne</td><td headers="c1-d3-job-header" class="job" style="background-color: #ffffff">TCH ASST PROF</td><td headers="c1-d3-tenure-header" class="tenure" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d3-empl-class-header" class="empclass" style="background-color: #ffffff">AL</td><td headers="c1-d3-presfte-header" style="background-color: #ffffff">1.00</td><td headers="c1-d3-propfte-header" style="background-color: #ffffff">1.00</td><td headers="c1-d3-pressal-header" class="right" style="background-color: #ffffff">$91,045.68</td><td headers="c1-d3-propsal-header" class="right" style="background-color: #ffffff">$94,232.28</td>\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n        <h3 id="c1-d4">470 - Agr &amp; Consumer Economics</h3>\r\n        <table id="c1-d4-salary-table">\r\n            <thead>\r\n                <tr>\r\n                    <th id="c1-d4-empl-header" class="empl-heading">Employee Name</th><th id="c1-d4-job-header" class="job-heading">Job Title</th><th id="c1-d4-tenure-header" class="ten-heading">Tenure</th><th id="c1-d4-empl-class-header" class="empclass-heading">Empl Class</th><th id="c1-d4-presfte-header" class="presfte-heading">Present FTE</th><th id="c1-d4-propfte-header" class="propfte-heading">Proposed FTE</th><th id="c1-d4-pressal-header" class="pressal-heading">Present Salary</th><th id="c1-d4-propsal-header" class="propsal-heading">Proposed Salary</th>\r\n                </tr>\r\n            </thead>\r\n            <tbody>\r\n                <tr id="c1-d4-e1-j1">\r\n                    <td headers="c1-d4-empl-header" class="empl" style="background-color: #d3d3d3">Arends-Kuenning, Mary Paula</td><td headers="c1-d4-job-header" class="job" style="background-color: #d3d3d3">PROF</td><td headers="c1-d4-tenure-header" class="tenure" style="background-color: #d3d3d3">A</td><td headers="c1-d4-empl-class-header" class="empclass" style="background-color: #d3d3d3">AA</td><td headers="c1-d4-presfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d4-propfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d4-pressal-header" class="right" style="background-color: #d3d3d3">$154,444.00</td><td headers="c1-d4-propsal-header" class="right" style="background-color: #d3d3d3">$155,988.44</td>\r\n                </tr>\r\n                <tr id="c1-d4-e1-total">\r\n                    <td headers="c1-d4-empl-header" class="empl" style="background-color: #ffffff">Arends-Kuenning, Mary Paula</td><td headers="c1-d4-job-header" class="italic-left" style="background-color: #ffffff">Employee Total for All Jobs</td><td headers="c1-d4-tenure-header" class="tenure" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d4-empl-class-header" class="empclass" style="background-color: #ffffff">&nbsp;</td><td headers="c1-d4-presfte-header" class="italic" style="background-color: #ffffff">1.00</td><td headers="c1-d4-propfte-header" class="italic" style="background-color: #ffffff">1.00</td><td headers="c1-d4-pressal-header" class="italic-right" style="background-color: #ffffff">$174,444.00</td><td headers="c1-d4-propsal-header" class="italic-right" style="background-color: #ffffff">$175,988.44</td>\r\n                </tr>\r\n                <tr id="c1-d4-e2-j1">\r\n                    <td headers="c1-d4-empl-header" class="empl" style="background-color: #d3d3d3">Atallah, Shady Salim</td><td headers="c1-d4-job-header" class="job" style="background-color: #d3d3d3">ASSOC PROF</td><td headers="c1-d4-tenure-header" class="tenure" style="background-color: #d3d3d3">A</td><td headers="c1-d4-empl-class-header" class="empclass" style="background-color: #d3d3d3">AA</td><td headers="c1-d4-presfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d4-propfte-header" style="background-color: #d3d3d3">1.00</td><td headers="c1-d4-pressal-header" class="right" style="background-color: #d3d3d3">$148,273.07</td><td headers="c1-d4-propsal-header" class="right" style="background-color: #d3d3d3">$156,279.82</td>\r\n                </tr>\r\n                <tr id="c1-d4-e2-total">\r\n                    <td headers="c1-d4-empl-header" class="empl" style="

In [30]:
processPage(rawHTML, "KP", "Grainger")

ACES Technology Services
ADM Institute for PHL
Ag Ldrshp Educ Comm Program
Agr &amp; Consumer Economics
Agr, Consumer &amp; Env Sci Admn
Agricultural &amp; Biological Engr
Animal Sciences
Cooperative Extension
Crop Sciences
Food Science &amp; Human Nutrition
Human Dvlpmt &amp; Family Studies

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

Natural Res &amp; Env Sci
Nutritional Sciences

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Department Name,College Code,College Name
0,"Kim, James H",DIR OF INFO TECHNOL,NaN,BA,1.0,1.0,"$115,000.00","$116,150.00",ACES Technology Services,KP,Grainger
1,"Meyer, Donald L",SR NETWORK ANLYS,NaN,BA,1.0,1.0,"$98,328.48","$99,311.76",ACES Technology Services,KP,Grainger
0,"McNamara, Paul E","DIR, ADMI",NaN,BA,0.0,0.0,"$15,000.00","$15,000.00",ADM Institute for PHL,KP,Grainger
1,"McNamara, Paul E",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$173,952.40","$175,541.92",ADM Institute for PHL,KP,Grainger
0,"Axtman-Barker, Pamela Ann",TCH ASST PROF,NaN,AL,1.0,1.0,"$79,950.00","$83,148.00",Ag Ldrshp Educ Comm Program,KP,Grainger
...,...,...,...,...,...,...,...,...,...,...,...
122,"Wang, Shulei",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$139,998.49","$143,078.46",Nutritional Sciences,KP,Grainger
123,"Woods, Jeffrey A",PROF,NaN,AA,0.0,0.0,$0.00,$0.00,Nutritional Sciences,KP,Grainger
124,"Woods, Jeffrey A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$277,449.00","$280,083.00",Nutritional Sciences,KP,Grainger
125,"Zhu, Ruoqing",ASSOC PROF,NaN,AA,0.0,0.0,$0.00,$0.00,Nutritional Sciences,KP,Grainger
126,"Zhu, Ruoqing",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$154,632.68","$158,034.60",Nutritional Sciences,KP,Grainger

In [32]:
from time import sleep

dfs = []
for i in range(len(collegeCodes)):
  print(f"=== {collegeName} ===")
  collegeCode = collegeCodes[i]
  collegeName = collegeNames[i]
  rawHTML = requests.get(urlList[i]).text
  dfs.append( processPage(rawHTML, collegeCode, collegeName) )
  sleep(5)

df = pd.concat(dfs)

=== Agr, Consumer & Env Sciences
 ===
ACES Technology Services
ADM Institute for PHL
Ag Ldrshp Educ Comm Program
Agr &amp; Consumer Economics
Agr, Consumer &amp; Env Sci Admn
Agricultural &amp; Biological Engr
Animal Sciences
Cooperative Extension

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

Crop Sciences
Food Science &amp; Human Nutrition
Human Dvlpmt &amp; Family Studies
Natural Res &amp; Env Sci
Nutritional Sciences
=== Agr, Consumer & Env Sciences
 ===
Applied Health Sciences Admin
Chez Veterans Center
Ctr Health, Aging, Disability
Disability Res &amp; Educ Svcs
Health and Kinesiology
Recreation, Sport and Tourism
Speech &amp; Hearing Science

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Applied Health Sciences
 ===
Armed Forces Coordinator

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Armed Forces
 ===
Aux. Health/WB Marketing
Division of Campus Recreation
Housing Division
Illini Union
McKinley Health Center
Office of the Dean of Students
Parking Department
Student Affairs Technology

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Auxiliary Units
 ===
Biomed &amp; Translational Sci
Carle IL COM Administration
Clinical Sciences

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Carle Illinois Medicine
 ===
Center Innov in Teach Learn
I

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Center Innov in Teach Learn
 ===
Faculty/Staff Assistance Svcs
Illinois Human Resources
News Bureau
Office of Public Engagement
Office of the Chancellor
Special Events
StratCommunications
Web Services

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Chancellor
 ===
Advertising
College of Media Admin
IPM Administration
IPM Content Information
IPM Content Production
IPM Content Programming
IPM Delivery
IPM Development
Inst of Communications Rsch
Journalism
Media and Cinema Studies

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== College of Media
 ===
Intercollegiate Athletics
State Farm Center

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Div Intercollegiate Athletics
 ===
Center Advising &amp; Acad Svcs

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Division of Exploratory Studies
 ===
Bureau Educational Research
Centers &amp;Strategic Initiatives
Council Teacher Ed Admin
Curriculum and Instruction
Educ Policy, Orgzn &amp; Leadrshp
Education Administration
Educational Psychology
Special Education

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Education
 ===
Energy Services Administration

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Energy Services
 ===
Bldg Maintenance Crafts/Trades
Capital Programs
F&amp;S Engineering Services
Facilities and Services

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Facilities
 ===
Architecture
Art &amp; Design
Dance
Fine &amp; Applied Arts Admin
Japan House
Krannert Art Museum
Krannert Center
Landscape Architecture
Music
Theatre
Urban &amp; Regional Planning

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Fine & Applied Arts
 ===
Accountancy
Business Administration
Business Online Programs
Ctr Business &amp; Public Policy
Disruption and Innovation
Finance
Gies Academic Programs
Gies Advancement
Gies Business Grad Programs
Gies College of Business
Gies Mktg &amp; Communications
Gies Undergraduate Programs
IT Partners Gies Business
Illinois Business Consulting
OV Office of Entrepreneurship
Office of Access and Community
Student &amp; Corporate Connection
Teaching and Learning

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Gies College of Business
 ===
Graduate Admin

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Graduate College
 ===
Aerospace Engineering
Applied Research Institute
Bioengineering
Civil &amp; Environmental Eng
Computational Science &amp; Engr
Coordinated Science Lab
Electrical &amp; Computer Eng

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

Engineering Administration
Engineering General Expen
Engineering IT Shared Services
Engr Shared Admin Services
Industrial&amp;Enterprise Sys Eng
Information Trust Institute
Materials Research Lab
Materials Science &amp; Engineerng
Mechanical Sci &amp; Engineering
Micro and Nanotechnology Lab
Nuclear, Plasma, &amp; Rad Engr
Physics
Siebel Center for Design
Siebel School Comp &amp; Data Sci

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

Technology Entrepreneur Ctr

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Grainger Engineering
 ===
Global Education &amp; Training
Illinois Abroad
Illinois International
Intensive English Institute
Intl Student and Scholar Svcs

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Illinois International
 ===
Law
Law Library

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Law
 ===
Actuarial Sci and Risk Mgmt
African American Studies
American Indian Studies Prgrm
Anthropology
Appl Tech Learning Arts &amp; Sciences
Asian American Studies
Astronomy
Biochemistry
Biophysics &amp; Quant Biology
Cell &amp; Developmental Biology
Center for African Studies
Center for Global Studies

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

Center for Writing Studies
Chemical &amp; Biomolecular Engr
Chemistry
Classics
Climate Meteorology &amp; Atm Sci
Cline Ctr for Adv Social Rsrch
Communication
Comparative &amp; World Literature
Ctr S. Asian &amp; MidEast Studies
E Asian &amp; Pacific Studies Cntr
E. Asian Languages &amp; Cultures
Earth Sci &amp; Environmental Chng
Economics
English

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

Entomology
European Union Center
Evolution Ecology Behavior
French and Italian
Gender and Women's Studies
Geography &amp; GIS
Germanic Languages &amp; Lit
Global Studies Prog &amp; Courses
History
Illinois Global Institute
LAS Administration
Latin American &amp; Carib Studies
Latina/Latino Studies
Lemann Center
Linguistics

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

Mathematics
Microbiology
Molecular &amp; Integrative Physl
Neuroscience Program
Philosophy
Plant Biology
Political Science
Prg in Jewish Culture &amp;Society
Program in Medieval Studies
Psychology
Religion
Russian,E European,Eurasn Ctr
Sch Earth, Soc, Environ Admin
Sch Lit, Cultures, Ling Adm
School of Chemical Sciences
School of Integrative Biology
School of Molecular &amp; Cell Bio

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

Slavic Languages &amp; Literature
Sociology
Spanish and Portuguese
Spurlock Museum
Statistics
Study of Global Gender Equity
The ACDIS Program
Translation &amp; Interpreting St
Unit For Criticism
=== Liberal Arts & Sciences
 ===
Beckman Institute
Cancer Center at Illinois
Humanities Research Institute
IL Natural History Survey
IL State Archaeological Survey
IL State Geological Survey
IL State Water Survey

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

IL Sustainable Technology Ctr
Inst for Sustain, Enrgy, &amp; Env
Institute for Genomic Biology
Interdis Health Sci Institute
Prairie Research Institute
Supercomputing Applications

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== OVCRI Institutes
 ===
Ofc VC Inst Advancement

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Ofc VC Inst Advancement
 ===
Big Ten Academic Alliance
Campus Honors Program
Center for Advanced Study
Div of Management Information
Enrollment Mgmt Shared Svcs
Office of Undergrad Research
Office of the Registrar
Osher Lifelong Learning Inst
Principal's Scholars Pgm
Provost/EVC Admin
SmartHealthyCommunity(Rokwire)
Student Financial Aid
UIUC Purchasing CMO
Undergraduate Admissions
University Laboratory HS

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Provost & Executive VC
 ===
Fire Service Institute
Police Training Institute

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Public Safety
 ===
Informatics
Information Sciences

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== School of Information Sciences
 ===
School of Labor &amp; Empl. Rel.

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== School of Labor & Empl. Rel.
 ===
School of Social Work

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== School of Social Work
 ===
Ofc of the Chief Info Officer
TS IT Service Delivery
Technology Services

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Technology Services
 ===
Library
Library Admin
Library Collections/Support
Library Research &amp; Publication
Mortenson Cntr Int'l Lib Prgms

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== University Library
 ===
Allerton Park &amp; Retreat Center
Division of Public Safety
Illini Center
Ofc of Strategic Project Mgmt
Office of Threat Assessment
VC Admin and Operations
Willard Airport Commercial Op

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== VC Admin and Operations
 ===
Counseling Center
Illinois Leadership Center
Inclusion &amp; Intercultural Rels
Jeffries Ctr Acces and AcadSuc
Student Conflict Resolution
Student Success and Engagement
The Career Center
VC Student Affairs

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== VC Student Affairs
 ===
Animal Care Program
Biotechnology Center
Division of Research Safety
EnterpriseWorks
IL Quantum &amp; Microelec Park
OVCRI Admin
Office of Animal Research Comp
Office of Corporate Relations
Office of Proposal Development
Office of Research Security
Protection of Research Subject
Sponsored Programs Admin

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== VC for Research and Innovation
 ===
Center for Zoonoses Research
Comparative Biosciences
Medical District Vet Clinic
Pathobiology
Vet Clinical Medicine
Vet Med College
Vet Medicine Administration
Veterinary Diagnostic Lab
Veterinary Prog in Agr
Veterinary Teaching Hospital

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

=== Veterinary Medicine
 ===
Office for Access and Equity
Title IX Office
Vice Chancellor for Diversity

C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]
C:\Users\waf\AppData\Local\Temp\ipykernel_36944\2376183851.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(h3_full)[0]

In [33]:
df

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Department Name,College Code,College Name
0,"Kim, James H",DIR OF INFO TECHNOL,NaN,BA,1.0,1.0,"$115,000.00","$116,150.00",ACES Technology Services,KL,"Agr, Consumer & Env Sciences\n"
1,"Meyer, Donald L",SR NETWORK ANLYS,NaN,BA,1.0,1.0,"$98,328.48","$99,311.76",ACES Technology Services,KL,"Agr, Consumer & Env Sciences\n"
0,"McNamara, Paul E","DIR, ADMI",NaN,BA,0.0,0.0,"$15,000.00","$15,000.00",ADM Institute for PHL,KL,"Agr, Consumer & Env Sciences\n"
1,"McNamara, Paul E",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$173,952.40","$175,541.92",ADM Institute for PHL,KL,"Agr, Consumer & Env Sciences\n"
0,"Axtman-Barker, Pamela Ann",TCH ASST PROF,NaN,AL,1.0,1.0,"$79,950.00","$83,148.00",Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences\n"
...,...,...,...,...,...,...,...,...,...,...,...
4,"Guerra Perez, Gioconda",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$294,590.25","$297,536.15",Vice Chancellor for Diversity,NV,Vice Chancellor for Diversity
5,"VanDuyne, Adam Jareb",EXEC DIR FIN & ADMN,NaN,BA,1.0,1.0,"$156,900.00","$158,469.00",Vice Chancellor for Diversity,NV,Vice Chancellor for Diversity
6,"Wantland, Ross A",DIR OF CURR DEVL & EDUC,NaN,BA,1.0,1.0,"$104,870.40","$105,919.10",Vice Chancellor for Diversity,NV,Vice Chancellor for Diversity
7,"Wantland, Ross A",INTERIM DIR AIE,NaN,BA,0.0,0.0,"$27,000.00","$27,000.00",Vice Chancellor for Diversity,NV,Vice Chancellor for Diversity
8,"Wantland, Ross A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$131,870.40","$132,919.10",Vice Chancellor for Diversity,NV,Vice Chancellor for Diversity

In [35]:
df[ df["Employee Name"].str.contains("Fagen") ]

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Department Name,College Code,College Name
75,"Fagen-Ulmschneider, Wade A","TCH PROF, CI MED",NaN,AA,0.0,0.0,$0.00,$0.00,Biomed &amp; Translational Sci,LT,Carle Illinois Medicine\n
76,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$176,000.00","$180,400.00",Biomed &amp; Translational Sci,LT,Carle Illinois Medicine\n
75,"Fagen-Ulmschneider, Wade A",TCH PROF,M,AA,1.0,1.0,"$176,000.00","$180,400.00",Siebel School Comp &amp; Data Sci,KP,Grainger Engineering\n
76,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$176,000.00","$180,400.00",Siebel School Comp &amp; Data Sci,KP,Grainger Engineering\n
29,"Fagen-Ulmschneider, Wade A",TCH PROF,NaN,AA,0.0,0.0,$0.00,$0.00,Statistics,KV,Liberal Arts & Sciences\n
30,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$176,000.00","$180,400.00",Statistics,KV,Liberal Arts & Sciences\n

In [ ]:
df["Proposed Salary"] = df["Proposed Salary"].replace('[\$,]', '', regex=True).astype(float)
df[ df["Employee Name"].str.contains("Fagen") ]

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Department Name,College Code,College Name
75,"Fagen-Ulmschneider, Wade A","TCH PROF, CI MED",NaN,AA,0.0,0.0,$0.00,0.0,Biomed &amp; Translational Sci,LT,Carle Illinois Medicine\n
76,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$176,000.00",180400.0,Biomed &amp; Translational Sci,LT,Carle Illinois Medicine\n
75,"Fagen-Ulmschneider, Wade A",TCH PROF,M,AA,1.0,1.0,"$176,000.00",180400.0,Siebel School Comp &amp; Data Sci,KP,Grainger Engineering\n
76,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$176,000.00",180400.0,Siebel School Comp &amp; Data Sci,KP,Grainger Engineering\n
29,"Fagen-Ulmschneider, Wade A",TCH PROF,NaN,AA,0.0,0.0,$0.00,0.0,Statistics,KV,Liberal Arts & Sciences\n
30,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$176,000.00",180400.0,Statistics,KV,Liberal Arts & Sciences\n

In [37]:
df["Present Salary"] = df["Present Salary"].replace('[\$,]', '', regex=True).astype(float)
df[ df["Employee Name"].str.contains("Fagen") ]

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Department Name,College Code,College Name
75,"Fagen-Ulmschneider, Wade A","TCH PROF, CI MED",NaN,AA,0.0,0.0,0.0,0.0,Biomed &amp; Translational Sci,LT,Carle Illinois Medicine\n
76,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,176000.0,180400.0,Biomed &amp; Translational Sci,LT,Carle Illinois Medicine\n
75,"Fagen-Ulmschneider, Wade A",TCH PROF,M,AA,1.0,1.0,176000.0,180400.0,Siebel School Comp &amp; Data Sci,KP,Grainger Engineering\n
76,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,176000.0,180400.0,Siebel School Comp &amp; Data Sci,KP,Grainger Engineering\n
29,"Fagen-Ulmschneider, Wade A",TCH PROF,NaN,AA,0.0,0.0,0.0,0.0,Statistics,KV,Liberal Arts & Sciences\n
30,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,176000.0,180400.0,Statistics,KV,Liberal Arts & Sciences\n

In [40]:
df["Department Name"] = df["Department Name"].str.replace('&amp;', '&')
df["College Name"] = df["College Name"].replace('&amp;', '&')
df["Department Name"] = df["Department Name"].str.strip()
df["College Name"] = df["College Name"].str.strip()
df[ df["Employee Name"].str.contains("Fagen") ]

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Department Name,College Code,College Name
75,"Fagen-Ulmschneider, Wade A","TCH PROF, CI MED",NaN,AA,0.0,0.0,0.0,0.0,Biomed & Translational Sci,LT,Carle Illinois Medicine
76,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,176000.0,180400.0,Biomed & Translational Sci,LT,Carle Illinois Medicine
75,"Fagen-Ulmschneider, Wade A",TCH PROF,M,AA,1.0,1.0,176000.0,180400.0,Siebel School Comp & Data Sci,KP,Grainger Engineering
76,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,176000.0,180400.0,Siebel School Comp & Data Sci,KP,Grainger Engineering
29,"Fagen-Ulmschneider, Wade A",TCH PROF,NaN,AA,0.0,0.0,0.0,0.0,Statistics,KV,Liberal Arts & Sciences
30,"Fagen-Ulmschneider, Wade A",Employee Total for All Jobs,NaN,NaN,1.0,1.0,176000.0,180400.0,Statistics,KV,Liberal Arts & Sciences

In [41]:
df.to_csv("GRAYBOOK-ALL_RAW.csv", index=False)

In [45]:
def process(dfE):
  df_jobs = dfE[ dfE["Job Title"] != "Employee Total for All Jobs" ]
  
  jobTitles = list(df_jobs["Job Title"].unique())
  depts = list(df_jobs["Department Name"].unique())
  
  highest_salary_row = df_jobs.nlargest(1, "Proposed Salary")
  jobTitles.remove(highest_salary_row["Job Title"].values[0])
  depts.remove(highest_salary_row["Department Name"].values[0])

  if len(jobTitles) == 0:
    jobTitles = ""
  if len(depts) == 0:
    depts = ""

  return {
    "Employee Name": highest_salary_row["Employee Name"].values[0],

    "Primary Job Title": highest_salary_row["Job Title"].values[0],
    "Department Name": highest_salary_row["Department Name"].values[0],
    "College Code": highest_salary_row["College Code"].values[0],
    "College Name": highest_salary_row["College Name"].values[0],

    "Present FTE": dfE["Present FTE"].max(),
    "Proposed FTE": dfE["Proposed FTE"].max(),
    "Present Salary": dfE["Present Salary"].max(),
    "Proposed Salary": dfE["Proposed Salary"].max(),

    "Tenure": highest_salary_row["Tenure"].values[0],
    "Empl Class": highest_salary_row["Empl Class"].values[0],

    "Secondary Job Titles": str(jobTitles),
    "Secondary Department Names": str(depts),
  }


d = []
for name in df["Employee Name"].unique():
  dfSingle = df[ df["Employee Name"] == name ]

  dfAllJobs = dfSingle[ dfSingle["Job Title"] == "Employee Total for All Jobs" ]

  if len(dfAllJobs) > 1:
    values = dfAllJobs["Present Salary"].values

    val = values[0]
    identicalName = False
    for v in values:
      if v != val:
        identicalName = True

    if identicalName:
      indexFilter = []
      if name == "Kumar, Praveen":
        indexFilter = [168, 169]
      # elif name == "Li, Bo":
      #   indexFilter = [50, 51, 52, 232, 233]
      # else:
      #   print("!!!")
        
      df1 = dfSingle[ dfSingle.index.isin(indexFilter) ]
      df2 = dfSingle[ ~dfSingle.index.isin(indexFilter) ]

      if len(df1) == 0:
        print("!!! " + name)
        print(dfSingle)
      else:
        d.append(process(df1))
        d.append(process(df2))
    else:
      d.append(process(dfSingle))
  else:
    d.append(process(dfSingle))

In [46]:
df_CLEAN = pd.DataFrame(d)

In [47]:
df_CLEAN.head(30)

,Employee Name,Primary Job Title,Department Name,College Code,College Name,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Tenure,Empl Class,Secondary Job Titles,Secondary Department Names
0,"Kim, James H",DIR OF INFO TECHNOL,ACES Technology Services,KL,"Agr, Consumer & Env Sciences",1.0,1.0,115000.00,116150.00,NaN,BA,,
1,"Meyer, Donald L",SR NETWORK ANLYS,ACES Technology Services,KL,"Agr, Consumer & Env Sciences",1.0,1.0,98328.48,99311.76,NaN,BA,,
2,"McNamara, Paul E",PROF,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,173952.40,175541.92,A,AA,"['DIR, ADMI']","['ADM Institute for PHL', 'Nutritional Science..."
3,"Axtman-Barker, Pamela Ann",TCH ASST PROF,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences",1.0,1.0,79950.00,83148.00,NaN,AL,,
4,"Korte, Debra Sue",TCH ASSOC PROF,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences",1.0,1.0,102763.74,105332.83,M,AA,['DIR LRNG INNOVATION & E-LRNG'],"['Agr, Consumer & Env Sci Admn']"
5,"Leman, Amy Marie",ASST PROF,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences",1.0,1.0,91829.24,93665.82,NaN,AA,,['Human Dvlpmt & Family Studies']
6,"Morgan, Eric Lee",ASSOC PROF,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences",1.0,1.0,96803.17,97771.20,NaN,AA,,"['Natural Res & Env Sci', 'Lemann Center']"
7,"Ochs, Gary Alan",INSTR,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences",1.0,1.0,85240.93,87371.95,NaN,AL,,
8,"Rosch, David Michael",ASSOC PROF,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences",1.0,1.0,108226.47,109308.73,NaN,AA,,['Human Dvlpmt & Family Studies']
9,"Smist, Jennifer Anne",TCH ASST PROF,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences",1.0,1.0,91045.68,94232.28,NaN,AL,,
10,"Arends-Kuenning, Mary Paula",PROF,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,174444.00,175988.44,A,AA,"['ASSOC DEAN, OIP']","['Agr, Consumer & Env Sci Admn', 'Center for G..."
11,"Atallah, Shady Salim",ASSOC PROF,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,148273.07,156279.82,A,AA,,['Latin American & Carib Studies']
12,"Baltz, James H",CMPUT ASST INST SPEC,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,91980.72,92900.53,NaN,BA,,
13,"Batts, Ryan M","EXT SPEC, FARM & FIN MGMT",Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,57041.12,60330.11,NaN,BA,,
14,"Bera, Anil K",PROF,Economics,KV,Liberal Arts & Sciences,1.0,1.0,217881.70,226599.93,A,AA,,"['Agr & Consumer Economics', 'Finance', 'Stati..."
15,"Blumthal, Meredith",INSTR,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,114250.00,117378.85,M,AA,"['DIR, FOOD & AGRIBUSINESS MGMT']",
16,"Brazee, Richard J",ASSOC PROF,Natural Res & Env Sci,KL,"Agr, Consumer & Env Sciences",1.0,1.0,83640.55,84476.96,A,AA,,['Agr & Consumer Economics']
17,"Breen, Daniel Joseph","ASST HEAD, BUS & STRATG PLNG",Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,124040.80,127021.62,NaN,BA,,
18,"Brockett, Jerry Michael",ACAD ADVR,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,63000.00,63000.00,NaN,BA,,
19,"Bullock, David S",PROF,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,155360.11,164681.72,A,AA,"['PROF, NCSA']",['Supercomputing Applications']
20,"Chong, Ian G",MGR-SYSTEMS SERVICES,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,97473.45,98448.18,NaN,BA,,
21,"Coppess, Jonathan W",ASSOC PROF,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,167844.58,175532.50,A,AA,"['GARDNER/FARM BUREAU ASSOC PROF', 'EXT SPEC']","['Cooperative Extension', 'Law']"
22,"Dall'Erba, Sandy",PROF,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,164370.70,166014.41,A,AA,,"['Latin American & Carib Studies', 'Lemann Cen..."
23,"Ellinger, Paul N",PROF,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,478126.01,482907.27,A,AA,,
24,"Elmore, Ailie Carlene",INSTRUCTOR,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,79500.00,84626.39,M,AA,,
25,"Endres, A Bryan",PROF,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,149772.73,160256.82,A,AA,['CSBS AFFILIATE'],"['Natural Res & Env Sci', 'Center for Global S..."
26,"Golish, Kelly",ASST DIR TAX MATERIALS,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,90899.95,91808.95,NaN,BA,,
27,"Goodrich, Brittney Kay",ASST PROF,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,133000.00,134330.00,P,AA,['EXT SPEC'],['Cooperative Extension']
28,"Goodrich, Ryan Jeffrey",CLIN ASST PROF,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,87000.00,87870.00,NaN,AA,['EXT SPEC'],['Cooperative Extension']
29,"Gundersen, Lisa Christine",LECTURER,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences",1.0,1.0,110394.42,112271.13,M,AA,,

In [48]:
df_CLEAN[df_CLEAN["Employee Name"].str.contains("Fagen")]

,Employee Name,Primary Job Title,Department Name,College Code,College Name,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Tenure,Empl Class,Secondary Job Titles,Secondary Department Names
949,"Fagen-Ulmschneider, Wade A",TCH PROF,Siebel School Comp & Data Sci,KP,Grainger Engineering,1.0,1.0,176000.0,180400.0,M,AA,"['TCH PROF, CI MED']","['Biomed & Translational Sci', 'Statistics']"

In [49]:
df_CLEAN[df_CLEAN["Employee Name"].str.contains("Flanagan")]

,Employee Name,Primary Job Title,Department Name,College Code,College Name,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Tenure,Empl Class,Secondary Job Titles,Secondary Department Names
3892,"Flanagan, Ryan P",SR LECTURER,English,KV,Liberal Arts & Sciences,1.0,1.0,62488.48,64050.69,NaN,AA,,
4069,"Flanagan, Karle Ann",TCH ASSOC PROF,Statistics,KV,Liberal Arts & Sciences,1.0,1.0,118875.20,122685.83,M,AA,['DIR INCLSV DATA SCI ED'],['LAS Administration']

In [50]:
df_CLEAN.sort_values("Present Salary")

,Employee Name,Primary Job Title,Department Name,College Code,College Name,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Tenure,Empl Class,Secondary Job Titles,Secondary Department Names
1184,"Moore, Henry R","CLIN ASSOC PROF, CI MED",Clinical Sciences,LT,Carle Illinois Medicine,0.0,0.0,0.00,0.00,NaN,AM,,
3171,"Choi, Hyungsoo",DEPT AFFL,Micro and Nanotechnology Lab,KP,Grainger Engineering,0.0,0.0,0.00,0.00,NaN,AA,,
1189,"Muthekepalli, Sudha R","CLIN ASST PROF, CI MED",Clinical Sciences,LT,Carle Illinois Medicine,0.0,0.0,0.00,0.00,NaN,AM,,
1190,"Nasreen, Nadia","CLIN ASST PROF, CI MED",Clinical Sciences,LT,Carle Illinois Medicine,0.0,0.0,0.00,0.00,NaN,AM,,
1191,"O'Connell, Joseph Michael","CLIN ASST PROF, CI MED",Clinical Sciences,LT,Carle Illinois Medicine,0.0,0.0,0.00,0.00,NaN,AM,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2926,"Killeen, Timothy L",PROF,Electrical & Computer Eng,KP,Grainger Engineering,1.0,1.0,935105.28,944456.33,A,AA,,['Climate Meteorology & Atm Sci']
1532,"Lunney, Barry","ASST VARSITY COACH, FTBAL",Intercollegiate Athletics,NU,Div Intercollegiate Athletics,1.0,1.0,1058000.00,1058000.00,NaN,BA,"['ASST VAR COACH, FTBAL (AUTO)']",
1622,"Whitman, Joshua H",DIR DIV INTERCOLLEGIATE ATHL,Intercollegiate Athletics,NU,Div Intercollegiate Athletics,1.0,1.0,1508000.00,1508000.00,NaN,BA,['DIR DIV INTER ATH (AUTO)'],
1616,"Underwood, Bradley",HEAD VARSITY COACH MEN BSKTBAL,Intercollegiate Athletics,NU,Div Intercollegiate Athletics,1.0,1.0,4408000.00,4408000.00,NaN,BA,['HEAD VAR COACH MBB (AUTO)'],
1449,"Bielema, Bret Arnold",HEAD VARSITY COACH FOOTBALL,Intercollegiate Athletics,NU,Div Intercollegiate Athletics,1.0,1.0,7708000.00,7708000.00,NaN,BA,['HEAD VAR COACH FTBALL (AUTO)'],

In [51]:
df_CLEAN.to_csv("GRAYBOOK-CLEAN.csv", index=False)

<hr>

In [6]:
df_college = pd.read_html(url)
df_college

[               Employee Name                     Job Title Tenure Empl Class  \
 0             Allison, James                    ASSOC PROF    NaN         AA
 1             Allison, James   Employee Total for All Jobs    NaN        NaN
 2          Ansell, Phillip J                    ASSOC PROF      A         AA
 3          Ansell, Phillip J  DIR, CENTER SUSTAIN AVIATION    NaN         BA
 4          Ansell, Phillip J   Employee Total for All Jobs    NaN        NaN
 ..                       ...                           ...    ...        ...
 88  Woollands, Robyn Michele                     ASST PROF      P         AA
 89  Woollands, Robyn Michele   Employee Total for All Jobs    NaN        NaN
 90   Wroblewski, Gabrielle E                 TCH ASST PROF      M         AA
 91        Zahedi Mehr, Negar                     ASST PROF      P         AA
 92        Zahedi Mehr, Negar   Employee Total for All Jobs    NaN        NaN

     Present FTE  Proposed FTE Present Salary Proposed Salary
 0           0.0           0.0          $0.00           $0.00
 1           1.0           1.0    $122,876.00     $127,901.00
 2           1.0           1.0    $125,439.00     $132,298.00
 3           0.0           0.0      $5,000.00       $5,000.00
 4           1.0           1.0    $130,439.00     $137,298.00
 ..          ...           ...            ...             ...
 88          1.0           1.0    $106,250.00     $110,500.00
 89          1.0           1.0    $106,250.00     $110,500.00
 90          1.0           1.0     $80,000.00      $83,200.00
 91          1.0           1.0    $107,782.00     $112,093.00
 92          1.0           1.0    $107,782.00     $112,093.00

 [93 rows x 8 columns],
                    Employee Name                    Job Title  Tenure  \
 0            Aboukhatwa, Mohamed                   SR RES SCI     NaN
 1      Bernhard, Jennifer Truman                     DIR, ARI     NaN
 2      Bernhard, Jennifer Truman  Employee Total for All Jobs     NaN
 3         Colina Morles, Eliezer                  SR RES ENGR     NaN
 4         Dalhaus, Jessica Lynne             ASST DIR FOR RES     NaN
 5           Ehrhardt, David Adam                  SR RES ENGR     NaN
 6            Elabd, Omar Mohamed             SR SOFTWARE ENGR     NaN
 7                 Eslami, Maryam                STAFF RES SCI     NaN
 8                  Fallaw, James             SR SOFTWARE ENGR     NaN
 9      Johnson, Nicole Eddington                 MANAGING DIR     NaN
 10      Krogstad, Daniel Vincent                   SR RES SCI     NaN
 11      Krogstad, Daniel Vincent  Employee Total for All Jobs     NaN
 12                    Lucic, Ana                STAFF RES SCI     NaN
 13             Ondrejcek, Michal             SR SOFTWARE ENGR     NaN
 14  Timmons, Alexandra Christina               STAFF RES ENGR     NaN
 15             Witmer, Ann-Perry                   SR RES SCI     NaN
 16             Witmer, Ann-Perry  Employee Total for All Jobs     NaN

    Empl Class  Present FTE  Proposed FTE Present Salary Proposed Salary
 0          BA          1.0           1.0    $109,772.00     $113,888.00
 1          BA          0.0           0.0     $15,000.00      $15,000.00
 2         NaN          1.0           1.0    $233,026.00     $241,751.00
 3          BA          1.0           1.0    $108,212.00     $111,458.00
 4          BA          1.0           1.0     $84,000.00      $87,360.00
 5          BA          1.0           1.0    $121,699.00     $126,263.00
 6          BA          1.0           1.0    $103,179.00     $107,564.00
 7          BA          1.0           1.0     $92,000.00      $95,680.00
 8          BA          1.0           1.0     $96,000.00      $99,360.00
 9          BA          1.0           1.0    $147,280.00     $154,644.00
 10         BA          1.0           1.0    $110,240.00     $116,854.00
 11        NaN          1.0           1.0    $110,240.00     $116,854.00
 12         BA          1.0           1.0     $95,319.00      $99,370.00
 13         BA          1.0           1.0     $93,000.00      $96,720.00
 14         BA          1.0           1.0     $70,875.00      $75,801.00
 15         BA          1.0           1.0    $103,966.00     $107,085.00
 16        NaN          1.0           1.0    $103,966.00     $107,085.00  ,
                       Employee Name                    Job Title Tenure  \
 0              Aksimentiev, Aleksei                         PROF    NaN
 1              Aksimentiev, Aleksei  Employee Total for All Jobs    NaN
 2                    Amos, Jennifer          DIR OF M.ENG. PRGMS    NaN
 3                    Amos, Jennifer         HAHN FACULTY SCHOLAR    NaN
 4                    Amos, Jennifer                TEACHING PROF      M
 ..                              ...                          ...    ...
 167                Zhao, Sihai Dave  Employee Total for All Jobs    NaN
 168                      Zhao, Yang                    ASST PROF    NaN
 169                      Zhao, Yang  Employee Total for All Jobs    NaN
 170  van der Donk, Wilfred Adrianus                         PROF    NaN
 171  van der Donk, Wilfred Adrianus  Employee Total for All Jobs    NaN

     Empl Class  Present FTE  Proposed FTE Present Salary Proposed Salary
 0           AA          0.0           0.0          $0.00           $0.00
 1          NaN          1.0           1.0    $141,698.00     $148,783.00
 2           BA          0.0           0.0      $5,000.00       $5,000.00
 3           AA          0.0           0.0          $0.00           $0.00
 4           AA          1.0           1.0    $119,756.00     $125,558.00
 ..         ...          ...           ...            ...             ...
 167        NaN          1.0           1.0    $135,475.46     $141,247.33
 168         AA          0.0           0.0          $0.00           $0.00
 169        NaN          1.0           1.0    $121,835.00     $127,266.00
 170         AA          0.0           0.0          $0.00           $0.00
 171        NaN          1.0           1.0    $281,681.54     $292,667.12

 [172 rows x 8 columns],
                 Employee Name                    Job Title Tenure Empl Class  \
 0             Al-Qadi, Imad L                   DIR, ATREL    NaN         BA
 1             Al-Qadi, Imad L                         PROF      A         AA
 2             Al-Qadi, Imad L  Employee Total for All Jobs    NaN        NaN
 3    Alipour Tabrizi, Mohamad                RES ASST PROF      M         AA
 4          Andrawes, Bassem O                         PROF      A         AA
 ..                        ...                          ...    ...        ...
 138            Zhang, Xiaojia                    ASST PROF      P         AA
 139            Zhang, Xiaojia         CRAWFORD FAC SCHOLAR    NaN         AA
 140            Zhang, Xiaojia  Employee Total for All Jobs    NaN        NaN
 141                 Zhao, Lei                    ASST PROF      P         AA
 142                 Zhao, Lei  Employee Total for All Jobs    NaN        NaN

      Present FTE  Proposed FTE Present Salary Proposed Salary
 0            0.0           0.0      $5,000.00       $5,000.00
 1            1.0           1.0    $261,403.00     $271,859.00
 2            1.0           1.0    $276,403.00     $286,859.00
 3            1.0           1.0     $99,275.00     $103,246.00
 4            1.0           1.0    $156,758.00     $167,596.00
 ..           ...           ...            ...             ...
 138          1.0           1.0    $110,823.00     $116,756.00
 139          0.0           0.0          $0.00           $0.00
 140          1.0           1.0    $110,823.00     $116,756.00
 141          1.0           1.0    $110,282.00     $114,693.00
 142          1.0           1.0    $110,282.00     $114,693.00

 [143 rows x 8 columns],
   Employee Name                    Job Title  Tenure Empl Class  Present FTE  \
 0   Olson, Luke                     DIR, CSE     NaN         BA          0.0
 1   Olson, Luke  Employee Total for All Jobs     NaN        NaN          1.0

    Proposed FTE Present Salary Proposed Salary
 0           0.0     $15,000.00      $15,000.00
 1           1.0    $215,000.00     $223,000.00  ,
              Employee Name                     Job Title Tenure Empl Class  \
 0        Abdelzaher, Tarek                          PROF      A         AA
 1        Abdelzaher, Tarek   Employee Total for All Jobs    NaN        NaN
 2           Adve, Sarita V                          PROF      A         AA
 3           Adve, Sarita V   Employee Total for All Jobs    NaN        NaN
 4    Adve, Vikram Sadanand                          PROF      A         AA
 ..                     ...                           ...    ...        ...
 308              Zhao, Han   Employee Total for All Jobs    NaN        NaN
 309          Zike, Heather  UGRAD PRGM COORD & ACAD ADVR    NaN         BA
 310          Zilles, Craig                          PROF      A         AA
 311          Zilles, Craig           SEVERNS FAC SCHOLAR    NaN         AA
 312          Zilles, Craig   Employee Total for All Jobs    NaN        NaN

      Present FTE  Proposed FTE Present Salary Proposed Salary
 0            1.0           1.0    $220,000.00     $228,800.00
 1            1.0           1.0    $220,000.00     $228,800.00
 2            1.0           1.0    $230,000.00     $240,000.00
 3            1.0           1.0    $230,000.00     $240,000.00
 4            1.0           1.0    $230,000.00     $240,000.00
 ..           ...           ...            ...             ...
 308          1.0           1.0    $136,000.00     $141,440.00
 309          1.0           1.0     $65,487.40      $68,106.40
 310          1.0           1.0    $185,000.00     $192,400.00
 311          0.0           0.0          $0.00           $0.00
 312          1.0           1.0    $185,000.00     $192,400.00

 [313 rows x 8 columns],
              Employee Name                    Job Title  Tenure Empl Class  \
 0        Abdelzaher, Tarek                    PROF, CSL     NaN         AA
 1        Abdelzaher, Tarek  Employee Total for All Jobs     NaN        NaN
 2           Adve, Sarita V                    PROF, CSL     NaN         AA
 3           Adve, Sarita V  Employee Total for All Jobs     NaN        NaN
 4    Adve, Vikram Sadanand                    PROF, CSL     NaN         AA
 ..                     ...                          ...     ...        ...
 291      Zhang, Richard Yi  Employee Total for All Jobs     NaN        NaN
 292          Zhao, Zhizhen              ASSOC PROF, CSL     NaN         AA
 293          Zhao, Zhizhen  Employee Total for All Jobs     NaN        NaN
 294      Zharnitsky, Vadim                    PROF, CSL     NaN         AA
 295      Zharnitsky, Vadim  Employee Total for All Jobs     NaN        NaN

      Present FTE  Proposed FTE Present Salary Proposed Salary
 0            0.0           0.0          $0.00           $0.00
 1            1.0           1.0    $220,000.00     $228,800.00
 2            0.0           0.0          $0.00           $0.00
 3            1.0           1.0    $230,000.00     $240,000.00
 4            0.0           0.0          $0.00           $0.00
 ..           ...           ...            ...             ...
 291          1.0           1.0    $121,695.00     $126,908.00
 292          0.0           0.0          $0.00           $0.00
 293          1.0           1.0    $150,000.00     $156,003.00
 294          0.0           0.0          $0.00           $0.00
 295          1.0           1.0    $110,988.04     $114,839.32

 [296 rows x 8 columns],
       Employee Name                    Job Title Tenure Empl Class  \
 0    Adve, Sarita V                         PROF    NaN         AA
 1    Adve, Sarita V  Employee Total for All Jobs    NaN        NaN
 2     Aggarwal, Anu                TCH ASST PROF      M         AA
 3       Allen, Jont                         PROF      A         AA
 4       Allen, Jont  Employee Total for All Jobs    NaN        NaN
 ..              ...                          ...    ...        ...
 369   Zhao, Zhizhen                   ASSOC PROF      A         AA
 370   Zhao, Zhizhen       EVERITT FACULTY FELLOW    NaN         AA
 371   Zhao, Zhizhen  Employee Total for All Jobs    NaN        NaN
 372    Zhu, Wenjuan                   ASSOC PROF      A         AA
 373    Zhu, Wenjuan  Employee Total for All Jobs    NaN        NaN

      Present FTE  Proposed FTE Present Salary Proposed Salary
 0            0.0           0.0          $0.00           $0.00
 1            1.0           1.0    $230,000.00     $240,000.00
 2            1.0           1.0     $97,951.00     $102,269.00
 3            1.0           1.0    $147,392.00     $151,322.00
 4            1.0           1.0    $147,392.00     $151,322.00
 ..           ...           ...            ...             ...
 369          1.0           1.0    $150,000.00     $156,003.00
 370          0.0           0.0          $0.00           $0.00
 371          1.0           1.0    $150,000.00     $156,003.00
 372          1.0           1.0    $133,630.00     $138,971.00
 373          1.0           1.0    $133,630.00     $138,971.00

 [374 rows x 8 columns],
             Employee Name                    Job Title  Tenure Empl Class  \
 0          Ahmad, Irfan S     EXEC DIR, INTERDISC INIT     NaN         BA
 1          Ahmad, Irfan S  Employee Total for All Jobs     NaN        NaN
 2         Al-Qadi, Imad L  DIR, SMART TRANS INFRA INIT     NaN         BA
 3         Al-Qadi, Imad L  Employee Total for All Jobs     NaN        NaN
 4    Albers, Stacey Lynne                    ACAD ADVR     NaN         BA
 ..                    ...                          ...     ...        ...
 132    Wright, Ashleigh R   ASSOC DIR OF INST FOR IDEA     NaN         BA
 133        Zhang, Yuanhui                         PROF     NaN         AA
 134        Zhang, Yuanhui  Employee Total for All Jobs     NaN        NaN
 135     Zollinger, Jana M                DIR OF ADVCMT     NaN         BA
 136     Zollinger, Jana M  Employee Total for All Jobs     NaN        NaN

      Present FTE  Proposed FTE Present Salary Proposed Salary
 0            1.0           1.0    $169,447.00     $174,522.00
 1            1.0           1.0    $169,447.00     $174,522.00
 2            0.0           0.0     $10,000.00      $10,000.00
 3            1.0           1.0    $276,403.00     $286,859.00
 4            1.0           1.0     $57,000.00      $57,000.00
 ..           ...           ...            ...             ...
 132          1.0           1.0    $104,500.00     $107,635.00
 133          0.0           0.0          $0.00           $0.00
 134          1.0           1.0    $178,280.79     $185,112.02
 135          0.5           0.5     $53,303.00      $55,702.00
 136          1.0           1.0    $106,606.00     $111,404.00

 [137 rows x 8 columns],
      Employee Name                Job Title  Tenure Empl Class  Present FTE  \
 0  Block, Daniel J  ENGR TEACHING LAB COORD     NaN         BA          1.0

    Proposed FTE Present Salary Proposed Salary
 0           1.0    $102,500.00     $106,600.00  ,
                    Employee Name                      Job Title  Tenure  \
 0       Bequette, Kaitlyn Louise                STUD EMPL COORD     NaN
 1   Booth, Kathleen Sharon Ervin                      BUS ANLYS     NaN
 2                   Buss, Palmer                     SR IT SPEC     NaN
 3                   Butler, Brad  ASSOC DIR WEB, APP, INFO SERV     NaN
 4                Chan, Michael G                        IT ARCH     NaN
 5              Hart, Mark Smylie          ASST DIR FOR RES SERV     NaN
 6                 Hurst, James R  EXEC DIR, ENGR IT SHARED SERV     NaN
 7                 Le, Thang Hong              SR WEB APP DEVLPR     NaN
 8                      Lee, John             HELP DESK SERV MGR     NaN
 9                 Lowe, Jordan T              SR WEB APP DEVLPR     NaN
 10              Penrose, Frank E                INFRA TEAM LEAD     NaN
 11              Penrose, Frank E                      SYST ENGR     NaN
 12              Penrose, Frank E    Employee Total for All Jobs     NaN
 13             Robbins, Elaine N       ASST DIR FOR INSTRN SERV     NaN
 14              Taraszka, Paul J            SR LINUX SYST ADMNR     NaN

    Empl Class  Present FTE  Proposed FTE Present Salary Proposed Salary
 0          BA          1.0           1.0     $69,061.00      $71,651.00
 1          BA          0.5           0.5     $36,353.00      $37,898.00
 2          BA          1.0           1.0     $66,655.00      $68,655.00
 3          BA          1.0           1.0    $124,110.00     $128,454.00
 4          BA          1.0           1.0    $113,681.00     $117,940.00
 5          BA          1.0           1.0    $105,717.00     $110,472.00
 6          BA          1.0           1.0    $149,040.00     $155,002.00
 7          BA          1.0           1.0    $111,237.00     $116,797.00
 8          BA          1.0           1.0     $85,432.00      $89,704.00
 9          BA          1.0           1.0    $111,237.00     $115,127.00
 10         BA          0.0           0.0      $2,500.08       $2,500.08
 11         BA          1.0           1.0    $115,000.00     $115,000.00
 12        NaN          1.0           1.0    $117,500.08     $117,500.08
 13         BA          1.0           1.0    $105,000.00     $108,413.00
 14         BA          1.0           1.0     $88,383.00      $88,383.00  ,
          Employee Name       Job Title  Tenure Empl Class  Present FTE  \
 0      Atwood, Kathy J  DIR OF ENGR HR     NaN         BA          1.0
 1  Ozier, Sarah Leanne  DIR OF ENGR HR     NaN         BA          1.0

    Proposed FTE Present Salary Proposed Salary
 0           1.0    $114,400.00     $120,120.00
 1           1.0    $107,000.00     $112,350.00  ,
           Employee Name                       Job Title Tenure Empl Class  \
 0        Allison, James                      ASSOC PROF      A         AA
 1        Allison, James  JERRY S DOBROVOLNY FAC SCHOLAR    NaN         AA
 2        Allison, James     Employee Total for All Jobs    NaN        NaN
 3     Bashir, Masooda N                      ASSOC PROF    NaN         AA
 4     Bashir, Masooda N     Employee Total for All Jobs    NaN        NaN
 ..                  ...                             ...    ...        ...
 81          Wang, Qiong        ARTHUR DAVIS FAC SCHOLAR    NaN         AA
 82          Wang, Qiong                      ASSOC PROF      A         AA
 83          Wang, Qiong     Employee Total for All Jobs    NaN        NaN
 84  Wooldridge, Abigail                       ASST PROF      P         AA
 85  Wooldridge, Abigail     Employee Total for All Jobs    NaN        NaN

     Present FTE  Proposed FTE Present Salary Proposed Salary
 0           1.0           1.0    $122,876.00     $127,901.00
 1           0.0           0.0          $0.00           $0.00
 2           1.0           1.0    $122,876.00     $127,901.00
 3           0.0           0.0          $0.00           $0.00
 4           1.0           1.0    $109,325.73     $113,695.00
 ..          ...           ...            ...             ...
 81          0.0           0.0          $0.00           $0.00
 82          1.0           1.0    $141,412.00     $146,368.00
 83          1.0           1.0    $141,412.00     $146,368.00
 84          1.0           1.0    $107,665.00     $112,068.00
 85          1.0           1.0    $107,665.00     $112,068.00

 [86 rows x 8 columns],
              Employee Name                    Job Title  Tenure Empl Class  \
 0        Abdelzaher, Tarek                    PROF, ITI     NaN         AA
 1        Abdelzaher, Tarek  Employee Total for All Jobs     NaN        NaN
 2           Adve, Sarita V                    PROF, ITI     NaN         AA
 3           Adve, Sarita V  Employee Total for All Jobs     NaN        NaN
 4    Adve, Vikram Sadanand                    PROF, ITI     NaN         AA

In [10]:
df_college[5]

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary
0,"Abdelzaher, Tarek",PROF,A,AA,1.0,1.0,"$220,000.00","$228,800.00"
1,"Abdelzaher, Tarek",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$220,000.00","$228,800.00"
2,"Adve, Sarita V",PROF,A,AA,1.0,1.0,"$230,000.00","$240,000.00"
3,"Adve, Sarita V",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$230,000.00","$240,000.00"
4,"Adve, Vikram Sadanand",PROF,A,AA,1.0,1.0,"$230,000.00","$240,000.00"
...,...,...,...,...,...,...,...,...
308,"Zhao, Han",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$136,000.00","$141,440.00"
309,"Zike, Heather",UGRAD PRGM COORD & ACAD ADVR,NaN,BA,1.0,1.0,"$65,487.40","$68,106.40"
310,"Zilles, Craig",PROF,A,AA,1.0,1.0,"$185,000.00","$192,400.00"
311,"Zilles, Craig",SEVERNS FAC SCHOLAR,NaN,AA,0.0,0.0,$0.00,$0.00
312,"Zilles, Craig",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$185,000.00","$192,400.00"

In [5]:
from time import sleep


dfs = []

for url in urlList:
  x = pd.read_html(url)
  college_df = x[0]
  college = college_df.iloc[0, 0]
  print(college)
  college.split(" - ")
  college_code, college_name = college.split(" - ")

  college_df = college_df.drop(index=[0])
  college_df["College Code"] = college_code
  college_df["College Name"] = college_name

  college_df = college_df.apply(f, axis=1)
  college_df = college_df.dropna(subset=["Department Code"])
  dfs.append(college_df)
  sleep(5)

Allison, James

ValueError: not enough values to unpack (expected 2, got 1)

In [62]:
df = pd.concat(dfs)
df.to_csv("graybook-2024.csv", index=False)